"""Create task table

Revision ID: 7b487b686b5f
Revises: 
Create Date: 2026-02-06 22:18:38.758225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b487b686b5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    taskstatus_enum = postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus', create_type=False)
    taskstatus_enum.create(op.get_bind(), checkfirst=True)

    taskpriority_enum = postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='taskpriority', create_type=False)
    taskpriority_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('task', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False, server_default='MEDIUM'))
    op.add_column('task', sa.Column('user_id', sa.String(length=255), nullable=False, server_default=''))
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               existing_nullable=False)
    op.alter_column('task', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('task', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_task_owner_id', table_name='task')
    op.create_index('idx_task_created_at', 'task', ['created_at'], unique=False)
    op.create_index('idx_task_status', 'task', ['status'], unique=False)
    op.create_index('idx_task_user_id', 'task', ['user_id'], unique=False)
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    op.drop_column('task', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('owner_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.drop_index('idx_task_user_id', table_name='task')
    op.drop_index('idx_task_status', table_name='task')
    op.drop_index('idx_task_created_at', table_name='task')
    op.create_index('ix_task_owner_id', 'task', ['owner_id'], unique=False)
    op.alter_column('task', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('task', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('task', 'user_id')
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###
