"""Create task table

Revision ID: 26a5f5175a71
Revises: 20260202204628
Create Date: 2026-02-02 21:47:30.581235

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '26a5f5175a71'
down_revision = '20260202204628'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
